// ------------------------------------------------------------------------------
//  <Autogenerated>
//    Generated By Dummy
//  </Autogenerated>
// ------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

#pragma warning disable
namespace Dummy.Dumbs.Types
{
    #region MaxDigitsAttribute
public class MaxDigitsAttribute : ValidationAttribute
{
        public MaxDigitsAttribute(int max, int min = 0)
        {
        }
}
#endregion
}
#pragma warning resbusinessre
