// ------------------------------------------------------------------------------
//  <Autogenerated>
//    Generated By Dummy
//  </Autogenerated>
// ------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

#pragma warning disable
namespace Dummy.Dumbs.Types
{
    [Serializable]
[DebuggerStepThrough]
[DesignerCategory("ruby")]
[XmlType(TypeName="DocumentGotcharubyType1", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
[XmlRoot(ElementName="DocumentGotcharubyType1")]
public partial class DocumentGotcharubyType1Xsd : DocumentGotcharubyTypeXsd
{
}
}
#pragma warning resbusinessre
