// ------------------------------------------------------------------------------
//  <Autogenerated>
//    Generated By Dummy
//  </Autogenerated>
// ------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

#pragma warning disable
namespace Dummy.Dumbs.Types
{
    /// <summary>
/// BDNDRUDT000005
/// </summary>
/// <summary>
/// UDT
/// </summary>
/// <summary>
/// Sound. Type
/// </summary>
/// <summary>
/// 1.0
/// </summary>
/// <summary>
/// An audio representation.
/// </summary>
/// <summary>
/// Sound
/// </summary>
/// <summary>
/// binary
/// </summary>

[Serializable]
[DebuggerStepThrough]
[DesignerCategory("ruby")]
[XmlType(Namespace="urn:oasis:names:specification:bdndr:schema:xsd:UnqualifiedDataTypes-1", TypeName="SoundType")]
[XmlRoot(ElementName="SoundType")]
public partial class SoundTypeXsd : BinaryObjectTypeXsd
{
}
}
#pragma warning resbusinessre
