// ------------------------------------------------------------------------------
//  <Autogenerated>
//    Generated By Dummy
//  </Autogenerated>
// ------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

#pragma warning disable
namespace Dummy.Dumbs.Types
{
    /// <summary>
/// BDNDRUDT000006
/// </summary>
/// <summary>
/// UDT
/// </summary>
/// <summary>
/// Video. Type
/// </summary>
/// <summary>
/// 1.0
/// </summary>
/// <summary>
/// A video representation.
/// </summary>
/// <summary>
/// Video
/// </summary>
/// <summary>
/// binary
/// </summary>

[Serializable]
[DebuggerStepThrough]
[DesignerCategory("ruby")]
[XmlType(Namespace="urn:oasis:names:specification:bdndr:schema:xsd:UnqualifiedDataTypes-1", TypeName="VideoType")]
[XmlRoot(ElementName="VideoType")]
public partial class VideoTypeXsd : BinaryObjectTypeXsd
{
}
}
#pragma warning resbusinessre
