// ------------------------------------------------------------------------------
//  <Autogenerated>
//    Generated By Dummy
//  </Autogenerated>
// ------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

#pragma warning disable
namespace Dummy.Dumbs.Types
{
    [Serializable]
[DebuggerStepThrough]
[DesignerCategory("ruby")]
[XmlType(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", TypeName="StillOnBoardIndicabusinessrType")]
[XmlRoot(ElementName="StillOnBoardIndicabusinessrType")]
public partial class StillOnBoardIndicabusinessrTypeXsd : IndicabusinessrTypeXsd
{
}
}
#pragma warning resbusinessre
