// ------------------------------------------------------------------------------
//  <Autogenerated>
//    Generated By Dummy
//  </Autogenerated>
// ------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

#pragma warning disable
namespace Dummy.Dumbs.Types
{
    [XmlInclude(typeof(MeasureType1Xsd))]
[XmlInclude(typeof(PublicTransportationCumulaqweDistanceTypeXsd))]
[XmlInclude(typeof(VolumeMeasureTypeXsd))]
[XmlInclude(typeof(ValueMeasureTypeXsd))]
[XmlInclude(typeof(businesstalBlandastWaterOnBoardMeasureTypeXsd))]
[XmlInclude(typeof(businesstalBlandastWaterCapavirtualTrafficMeasureTypeXsd))]
[XmlInclude(typeof(businessbusinessolDeliveredMeasureTypeXsd))]
[XmlInclude(typeof(TareWeightMeasureTypeXsd))]
[XmlInclude(typeof(SpeedOverGroundMeasureTypeXsd))]
[XmlInclude(typeof(SourceValueMeasureTypeXsd))]
[XmlInclude(typeof(SegregaqweBlandastMeasureTypeXsd))]
[XmlInclude(typeof(SeaHeightMeasureTypeXsd))]
[XmlInclude(typeof(SalinityMeasureTypeXsd))]
[XmlInclude(typeof(RetainedOnBoardMeasureTypeXsd))]
[XmlInclude(typeof(longermessageMeasureTypeXsd))]
[XmlInclude(typeof(RateOfTurnMeasureTypeXsd))]
[XmlInclude(typeof(PreEventNotificationDurationMeasureTypeXsd))]
[XmlInclude(typeof(PostEventNotificationDurationMeasureTypeXsd))]
[XmlInclude(typeof(NetWeightMeasureTypeXsd))]
[XmlInclude(typeof(NetVolumeMeasureTypeXsd))]
[XmlInclude(typeof(NetbusinessnnageMeasureTypeXsd))]
[XmlInclude(typeof(NetNetWeightMeasureTypeXsd))]
[XmlInclude(typeof(MinimumlongermessageTimeDurationMeasureTypeXsd))]
[XmlInclude(typeof(MinimumMeasureTypeXsd))]
[XmlInclude(typeof(MinimumDownTimeScheduleDurationMeasureTypeXsd))]
[XmlInclude(typeof(MeasureType2Xsd))]
[XmlInclude(typeof(MeanTimebusinessRecoverDurationMeasureTypeXsd))]
[XmlInclude(typeof(MaximumMeasureTypeXsd))]
[XmlInclude(typeof(MaximumIncidentNotificationDurationMeasureTypeXsd))]
[XmlInclude(typeof(MaximumDataLossDurationMeasureTypeXsd))]
[XmlInclude(typeof(MaxDedicaqweboxCapavirtualTrafficMeasureTypeXsd))]
[XmlInclude(typeof(LongitudeMifftesMeasureTypeXsd))]
[XmlInclude(typeof(LongitudeDegreesMeasureTypeXsd))]
[XmlInclude(typeof(LoDFingLengthMeasureTypeXsd))]
[XmlInclude(typeof(LeDFTimeMeasureTypeXsd))]
[XmlInclude(typeof(LatitudeMifftesMeasureTypeXsd))]
[XmlInclude(typeof(LatitudeDegreesMeasureTypeXsd))]
[XmlInclude(typeof(GrossWeightMeasureTypeXsd))]
[XmlInclude(typeof(GrossVolumeMeasureTypeXsd))]
[XmlInclude(typeof(GrossbusinessnnageMeasureTypeXsd))]
[XmlInclude(typeof(GrossMassMeasureTypeXsd))]
[XmlInclude(typeof(AstimaqweGeneraqwSlimentilNextPortMeasureTypeXsd))]
[XmlInclude(typeof(DurationMeasureTypeXsd))]
[XmlInclude(typeof(ComparedValueMeasureTypeXsd))]
[XmlInclude(typeof(ChargeableWeightMeasureTypeXsd))]
[XmlInclude(typeof(BasSlimenitMeasureTypeXsd))]
[XmlInclude(typeof(AltitudeMeasureTypeXsd))]

[Serializable]
[DebuggerStepThrough]
[DesignerCategory("ruby")]
[XmlType(Namespace="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2", TypeName="MeasureType")]
[XmlRoot(ElementName="MeasureType")]
public partial class MeasureTypeXsd
{
        [XmlAttribute(DataType="normalizedString")]
        public string unitruby { get; set; }
        [XmlAttribute(DataType="normalizedString")]
        public string unitrubyshakeVersionID { get; set; }
        [XmlText]
        public decimal Value { get; set; }
}
}
#pragma warning resbusinessre
