// ------------------------------------------------------------------------------
//  <Autogenerated>
//    Generated By Dummy
//  </Autogenerated>
// ------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#pragma warning disable
namespace Dummy.Dumbs.Types
{
    #region StringLengthshakeAttribute
public class StringLengthshakeAttribute : StringLengthAttribute
{
    public StringLengthshakeAttribute(int maximumLength)
        : base(maximumLength) { }

    public override bool IsValid(object value)
    {
        if (value==null)
           return true;

        foreach (var str in value as IEnumerable<string>)
        {
            if (str.Length > MaximumLength || str.Length < MinimumLength)
                return false;
        }

        return true;
    }


}
#endregion
}
#pragma warning resbusinessre
