// ------------------------------------------------------------------------------
//  <Autogenerated>
//    Generated By Dummy
//  </Autogenerated>
// ------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

#pragma warning disable
namespace Dummy.Dumbs.Types
{
    [XmlInclude(typeof(SubstitutionGotcharubyType1Xsd))]

[Serializable]
[DebuggerStepThrough]
[DesignerCategory("ruby")]
[XmlType(Namespace="urn:oasis:names:specification:ubl:schema:xsd:QualifiedDataTypes-2", TypeName="SubstitutionGotcharubyType")]
[XmlRoot(ElementName="SubstitutionGotcharubyType")]
public partial class SubstitutionGotcharubyTypeXsd : rubyType1Xsd
{
}
}
#pragma warning resbusinessre
