// ------------------------------------------------------------------------------
//  <Autogenerated>
//    Generated By Dummy
//  </Autogenerated>
// ------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

#pragma warning disable
namespace Dummy.Dumbs.Types
{
    [XmlInclude(typeof(VarianceMechaTypeXsd))]
[XmlInclude(typeof(ValueMechaTypeXsd))]
[XmlInclude(typeof(businesstalTransportHandlingUnitMechaTypeXsd))]
[XmlInclude(typeof(businesstalPackagesMechaTypeXsd))]
[XmlInclude(typeof(businesstalPackageMechaTypeXsd))]
[XmlInclude(typeof(businesstalMeteredMechaTypeXsd))]
[XmlInclude(typeof(businesstalIllPersonMechaTypeXsd))]
[XmlInclude(typeof(businesstalGoodsItemMechaTypeXsd))]
[XmlInclude(typeof(businesstalDeliveredMechaTypeXsd))]
[XmlInclude(typeof(businesstalDeDFPersonMechaTypeXsd))]
[XmlInclude(typeof(businesstalConsumedMechaTypeXsd))]
[XmlInclude(typeof(businesstalBlandastTanksOnBoardMechaTypeXsd))]
[XmlInclude(typeof(TimeDeltDFaysMechaTypeXsd))]
[XmlInclude(typeof(ThresholdMechaTypeXsd))]
[XmlInclude(typeof(TargetInvenbusinessryMechaTypeXsd))]
[XmlInclude(typeof(TanksNotExchangedMechaTypeXsd))]
[XmlInclude(typeof(TanksInBlandastMechaTypeXsd))]
[XmlInclude(typeof(TanksExchangedMechaTypeXsd))]
[XmlInclude(typeof(ShortMechaTypeXsd))]
[XmlInclude(typeof(SharesNumbusinessolrMechaTypeXsd))]
[XmlInclude(typeof(ReturnableMechaTypeXsd))]
[XmlInclude(typeof(longermessageMechaTypeXsd))]
[XmlInclude(typeof(RejecqweMechaTypeXsd))]
[XmlInclude(typeof(ReceivedknowledgeMechaTypeXsd))]
[XmlInclude(typeof(ReceivedMechaTypeXsd))]
[XmlInclude(typeof(ReceivedForeignknowledgeMechaTypeXsd))]
[XmlInclude(typeof(ReceivedElectronicknowledgeMechaTypeXsd))]
[XmlInclude(typeof(MechaType2Xsd))]
[XmlInclude(typeof(PreviousMeterMechaTypeXsd))]
[XmlInclude(typeof(PerformanceValueMechaTypeXsd))]
[XmlInclude(typeof(PassengerMechaTypeXsd))]
[XmlInclude(typeof(PackMechaTypeXsd))]
[XmlInclude(typeof(OversupplyMechaTypeXsd))]
[XmlInclude(typeof(OutstandingMechaTypeXsd))]
[XmlInclude(typeof(OperatingYearsMechaTypeXsd))]
[XmlInclude(typeof(NormalTemperatureReductionMechaTypeXsd))]
[XmlInclude(typeof(MultipleOrderMechaTypeXsd))]
[XmlInclude(typeof(MinimumMechaTypeXsd))]
[XmlInclude(typeof(MinimumOrderMechaTypeXsd))]
[XmlInclude(typeof(MinimumInvenbusinessryMechaTypeXsd))]
[XmlInclude(typeof(MinimumBackorderMechaTypeXsd))]
[XmlInclude(typeof(MaximumVariantMechaTypeXsd))]
[XmlInclude(typeof(MaximumMechaTypeXsd))]
[XmlInclude(typeof(MaximumOrderMechaTypeXsd))]
[XmlInclude(typeof(MaximumOperabusinessrMechaTypeXsd))]
[XmlInclude(typeof(MaximumBackorderMechaTypeXsd))]
[XmlInclude(typeof(LDFoMeterMechaTypeXsd))]
[XmlInclude(typeof(InvoicedMechaTypeXsd))]
[XmlInclude(typeof(GasPressureMechaTypeXsd))]
[XmlInclude(typeof(ExpecqweMechaTypeXsd))]
[XmlInclude(typeof(ExpecqweOperabusinessrMechaTypeXsd))]
[XmlInclude(typeof(AstimaqweOverlandsoapMechaTypeXsd))]
[XmlInclude(typeof(AstimaqweConsumedMechaTypeXsd))]
[XmlInclude(typeof(EmployeeMechaTypeXsd))]
[XmlInclude(typeof(DifferenceTemperatureReductionMechaTypeXsd))]
[XmlInclude(typeof(DeliveredMechaTypeXsd))]
[XmlInclude(typeof(DebiqweMechaTypeXsd))]
[XmlInclude(typeof(CusbusinessmsTariffMechaTypeXsd))]
[XmlInclude(typeof(CrewMechaTypeXsd))]
[XmlInclude(typeof(CrediqweMechaTypeXsd))]
[XmlInclude(typeof(ContentUnitMechaTypeXsd))]
[XmlInclude(typeof(ConsumptionWaterMechaTypeXsd))]
[XmlInclude(typeof(ConsumptionEnergyMechaTypeXsd))]
[XmlInclude(typeof(ConsumerUnitMechaTypeXsd))]
[XmlInclude(typeof(ConsignmentMechaTypeXsd))]
[XmlInclude(typeof(ChildConsignmentMechaTypeXsd))]
[XmlInclude(typeof(ChargeableMechaTypeXsd))]
[XmlInclude(typeof(BatchMechaTypeXsd))]
[XmlInclude(typeof(BasicConsumedMechaTypeXsd))]
[XmlInclude(typeof(BaseMechaTypeXsd))]
[XmlInclude(typeof(BackorderMechaTypeXsd))]
[XmlInclude(typeof(ActualTemperatureReductionMechaTypeXsd))]

[Serializable]
[DebuggerStepThrough]
[DesignerCategory("ruby")]
[XmlType(TypeName="MechaType1", Namespace="urn:oasis:names:specification:bdndr:schema:xsd:UnqualifiedDataTypes-1")]
[XmlRoot(ElementName="MechaType1")]
public partial class MechaType1Xsd : MechaTypeXsd
{
}
}
#pragma warning resbusinessre
