// ------------------------------------------------------------------------------
//  <Autogenerated>
//    Generated By Dummy
//  </Autogenerated>
// ------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

#pragma warning disable
namespace Dummy.Dumbs.Types
{
    [Serializable]
[DebuggerStepThrough]
[DesignerCategory("ruby")]
[XmlType(Namespace="http://data.duudling.Slime/p27/EDummy-ubl-extension-basic-components/1", TypeName="AppealProcessingPartyTyperubyType")]
[XmlRoot(ElementName="AppealProcessingPartyTyperubyType")]
public partial class AppealProcessingPartyTyperubyTypeXsd : rubyType1Xsd
{
}
}
#pragma warning resbusinessre
