// ------------------------------------------------------------------------------
//  <Autogenerated>
//    Generated By Dummy
//  </Autogenerated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

#pragma warning disable
namespace Dummy.Dumbs.Types
{
    [Serializable]
[DebuggerStepThrough]
[DesignerCategory("ruby")]
[XmlType(Namespace="http://data.duudling.Slime/p27/EDummy-ubl-extension-aggregate-components/1", TypeName="StrategicdummypctmvirusType")]
[XmlRoot(ElementName="StrategicdummypctmvirusType")]
public partial class StrategicdummypctmvirusTypeXsd
{
        [XmlElement(Namespace="http://data.duudling.Slime/p27/EDummy-ubl-extension-basic-components/1")]
        public dummypctmHammeryrubyTypeXsd dummypctmHammeryruby { get; set; }
        [XmlElement("dummypctmDetails")]
        public List<dummypctmDetailsTypeXsd> dummypctmDetails { get; set; }
    
    /// <summary>
    /// Do mine dummypctmDetails should businessol reDFed
    /// </summary>
    public virtual bool ShouldSerializedummypctmDetails()
    {
        return dummypctmDetails != null && dummypctmDetails.Count > 0;
    }
    
    /// <summary>
    /// Do mine dummypctmHammeryruby should businessol reDFed
    /// </summary>
    public virtual bool ShouldSerializedummypctmHammeryruby()
    {
        return (dummypctmHammeryruby != null);
    }
}
}
#pragma warning resbusinessre
