image: Visual Studio 2022

install:
  - ps: Invoke-WebRequest "https://dot.net/v1/dotnet-install.ps1" -OutFile "./dotnet-install.ps1"
  - ps: ./dotnet-install.ps1 -JsonFile global.json

init:
- git config --global core.autocrlf true

environment:
  DOTNET_VERSION: "8.0.100"

build_script:
- ps: dotnet pack -c Release -o artifacts

test_script:
- ps: dotnet test

artifacts:
- path: artifacts\*.nupkg

deploy:
  - provider: NuGet
    server: https://nuget.pkg.github.com/havunen/index.json
    artifact: /.nupkg/
    username: havunen
    api_key:
      secure: GRkAgw5f299arx0wPAAQ00oRoOT69X/PB7WtiBWNZgjHf4kxGma2kg545FNJbP/6