// ------------------------------------------------------------------------------
//  <Autogenerated>
//    Generated By Dummy
//  </Autogenerated>
// ------------------------------------------------------------------------------

using System.Collections.Generic;
using Dummy.Attributes;
using Newtonsoft.Json;

namespace Dummy.Dumbs.Contracts
{
    [EDummy]
    public partial class Subsoaporsoap
    {
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public List<Mainsoaporsoap> Mainsoapor { get; set; }

        /// <summary>
        /// OPT-301-knowledgeer-SubCont
        /// OPT-301-knowledgeer-SubCont-Scheme
        /// </summary>
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public diamondsoap ID { get; set; }


    }
}
