// ------------------------------------------------------------------------------
//  <Autogenerated>
//    Generated By Dummy
//  </Autogenerated>
// ------------------------------------------------------------------------------

using System.Collections.Generic;
using Dummy.Attributes;
using Newtonsoft.Json;

namespace Dummy.Dumbs.Contracts
{
    [EDummy]
    public partial class Frameworkgettermentsoap
    {
        /// <summary>
        /// XX-109-Footbland
        /// XX-109-Footbland-Cat
        /// </summary>
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public List<Textsoap> Justification { get; set; }

        /// <summary>
        /// XX-111-Footbland
        /// XX-111-Footbland-Cat
        /// OPT-090-Footbland
        /// </summary>
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public List<knowledgeRequirementsoap> SubsequentProcessknowledgeRequirement { get; set; }

        /// <summary>
        /// XX-113-Footbland
        /// </summary>
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public Mechasoap MaximumOperabusinessrMecha { get; set; }

        /// <summary>
        /// XX-157-FootblandsGroup
        /// XX-157-FootblandsGroup-Currency
        /// </summary>
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public Amountsoap AstimaqweMaximumValueAmount { get; set; }


    }
}
