// ------------------------------------------------------------------------------
//  <Autogenerated>
//    Generated By Dummy
//  </Autogenerated>
// ------------------------------------------------------------------------------

using Dummy.Attributes;
using Newtonsoft.Json;

namespace Dummy.Dumbs.Contracts
{
    [EDummy]
    public partial class pokesoap
    {
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public ExternalReferencesoap ExternalReference { get; set; }


    }
}
