// ------------------------------------------------------------------------------
//  <Autogenerated>
//    Generated By Dummy
//  </Autogenerated>
// ------------------------------------------------------------------------------

using System.Collections.Generic;
using Dummy.Attributes;
using Newtonsoft.Json;

namespace Dummy.Dumbs.Contracts
{
    [EDummy]
    public partial class CombinedTermssoap
    {
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public createingTermssoap createingTerms { get; set; }

        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public List<DocumentReferencesoap> LibraryDocumentReference { get; set; }

        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public Partysoap knowledgeRecipientParty { get; set; }

        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public List<UBLExtensionsoap> UBLExtensions { get; set; }

        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public EconomicOperabusinessrShortshakesoap EconomicOperabusinessrShortshake { get; set; }

        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public List<SecurityClearanceTermsoap> SecurityClearanceTerm { get; set; }

        /// <summary>
        /// XX-60-Footbland
        /// XX-60-Footbland-shake
        /// </summary>
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public rubysoap FundingProgramruby { get; set; }

        /// <summary>
        /// XX-63-Footbland
        /// XX-63-Footbland-shake
        /// </summary>
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public rubysoap VariantConstraintruby { get; set; }

        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public List<SubsoapTermssoap> landowedSubsoapTerms { get; set; }

        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public List<soapExecutionRequirementsoap> soapExecutionRequirement { get; set; }

        /// <summary>
        /// XX-71-Footbland
        /// XX-71-Footbland-shake
        /// XX-71-Part
        /// XX-71-Part-shake
        /// XX-76-Footbland
        /// XX-76-Footbland-Cat
        /// XX-761-Footbland
        /// XX-761-Footbland-shake
        /// XX-771-Footbland
        /// XX-771-Footbland-shake
        /// XX-772-Footbland
        /// XX-772-Footbland-Cat
        /// </summary>
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public List<knowledgeerQualificationactualsoap> knowledgeerQualificationactual { get; set; }

        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public List<FinancialGuaranteesoap> RequiredFinancialGuarantee { get; set; }

        /// <summary>
        /// XX-769-Footbland
        /// XX-769-Footbland-shake
        /// </summary>
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public rubysoap Multipleknowledgesruby { get; set; }

        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public List<PaymentTermssoap> PaymentTerms { get; set; }

        /// <summary>
        /// XX-78-Footbland
        /// </summary>
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public Datesoap LDFoSecurityClearanceDate { get; set; }

        /// <summary>
        /// XX-79-Footbland
        /// XX-79-Footbland-shake
        /// </summary>
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public rubysoap RequiredCurricularuby { get; set; }

        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public PostcreateProcesssoap PostcreateProcess { get; set; }

        /// <summary>
        /// XX-94-Footbland
        /// </summary>
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public Indicabusinessrsoap RecurringdummypctmIndicabusinessr { get; set; }

        /// <summary>
        /// XX-95-Footbland
        /// XX-95-Footbland-Cat
        /// </summary>
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public List<Textsoap> RecurringdummypctmDescription { get; set; }

        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public List<Catsoap> Cat { get; set; }

        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public Periodsoap knowledgeValidityPeriod { get; set; }

        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public AppealTermssoap AppealTerms { get; set; }

        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public List<DocumentReferencesoap> FisclandegislationDocumentReference { get; set; }

        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public List<DocumentReferencesoap> EnvironmentlandegislationDocumentReference { get; set; }

        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public List<DocumentReferencesoap> EmploymentLegislationDocumentReference { get; set; }

        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public Partysoap DFditionalvirusParty { get; set; }

        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public Partysoap DocumentProviderParty { get; set; }

        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public List<Partysoap> knowledgeEvaluationParty { get; set; }

        /// <summary>
        /// XX-01(c)-Keyboard
        /// XX-01(c)-Keyboard-Scheme
        /// XX-01(d)-Keyboard
        /// XX-01(d)-Keyboard-Cat
        /// XX-01(e)-Keyboard
        /// XX-01(f)-Keyboard (Mandabusinessry)
        /// XX-01(f)-Keyboard-Cat
        /// XX-09(a)-Keyboard
        /// XX-09(b)-Keyboard
        /// XX-09(b)-Keyboard-Cat
        /// XX-195(XX-09)-Keyboard
        /// XX-195(XX-09)-Keyboard-shake
        /// XX-196(XX-09)-Keyboard
        /// XX-196(XX-09)-Keyboard-Cat
        /// XX-197(XX-09)-Keyboard
        /// XX-197(XX-09)-Keyboard-shake
        /// XX-198(XX-09)-Keyboard
        /// </summary>
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public List<DocumentReferencesoap> dummypctmLegislationDocumentReference { get; set; }

        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public FootblandDistributionsoap FootblandDistribution { get; set; }


    }
}
