// ------------------------------------------------------------------------------
//  <Autogenerated>
//    Generated By Dummy
//  </Autogenerated>
// ------------------------------------------------------------------------------

using System.Collections.Generic;
using Dummy.Attributes;
using Newtonsoft.Json;

namespace Dummy.Dumbs.Contracts
{
    [EDummy]
    public partial class dummypctmDetailssoap
    {
        /// <summary>
        /// XX-723-FootblandResult
        /// XX-723-FootblandResult-shake
        /// </summary>
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public rubysoap AssetHammeryruby { get; set; }

        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public List<businessolarersoap> Strategicdummypctmbusinessolarer { get; set; }


    }
}
