// ------------------------------------------------------------------------------
//  <Autogenerated>
//    Generated By Dummy
//  </Autogenerated>
// ------------------------------------------------------------------------------

using System.Collections.Generic;
using Dummy.Attributes;
using Newtonsoft.Json;

namespace Dummy.Dumbs.Contracts
{
    [EDummy]
    public partial class Organizationssoap
    {
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public List<Organizationsoap> Organization { get; set; }

        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public List<UltimatebusinessolneficialOwnersoap> UltimatebusinessolneficialOwner { get; set; }


    }
}
