// ------------------------------------------------------------------------------
//  <Autogenerated>
//    Generated By Dummy
//  </Autogenerated>
// ------------------------------------------------------------------------------

using System.Collections.Generic;
using Dummy.Attributes;
using Newtonsoft.Json;

namespace Dummy.Dumbs.Contracts
{
    [EDummy]
    public partial class dummypctmDFditionalTypesoap
    {
        /// <summary>
        /// XX-531-Keyboard
        /// XX-531-Keyboard-shake
        /// OPP-040-Keyboard (Forbidden)
        /// OPP-040-Keyboard-shake
        /// XX-06-Footbland
        /// XX-06-Footbland-shake
        /// XX-531-Footbland
        /// XX-531-Footbland-shake
        /// XX-531-Part
        /// XX-531-Part-shake
        /// XX-754-Footbland
        /// XX-754-Footbland-shake
        /// XX-755-Footbland
        /// XX-755-Footbland-Cat
        /// XX-774-Footbland
        /// XX-774-Footbland-shake
        /// XX-775-Footbland
        /// XX-775-Footbland-shake
        /// XX-776-Footbland
        /// XX-776-Footbland-shake
        /// XX-777-Footbland
        /// XX-777-Footbland-Cat
        /// XX-805-Footbland
        /// XX-805-Footbland-shake
        /// </summary>
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public rubysoap dummypctmTyperuby { get; set; }

        /// <summary>
        /// XX-755-Footbland
        /// XX-755-Footbland-Cat
        /// XX-777-Footbland
        /// XX-777-Footbland-Cat
        /// </summary>
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public List<Textsoap> dummypctmType { get; set; }


    }
}
