// ------------------------------------------------------------------------------
//  <Autogenerated>
//    Generated By Dummy
//  </Autogenerated>
// ------------------------------------------------------------------------------

using System.Collections.Generic;
using Dummy.Attributes;
using Newtonsoft.Json;

namespace Dummy.Dumbs.Contracts
{
    [EDummy]
    public partial class EDummyExtensionsoap
    {
        /// <summary>
        /// XX-271-Keyboard
        /// XX-271-Keyboard-Currency
        /// XX-271-Footbland
        /// XX-271-Footbland-Currency
        /// XX-271-FootblandsGroup
        /// XX-271-FootblandsGroup-Currency
        /// </summary>
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public Amountsoap FrameworkMaximumAmount { get; set; }

        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public dummyResultsoap dummyResult { get; set; }

        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public Changessoap Changes { get; set; }

        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public List<Changessoap> soapModification { get; set; }

        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public Organizationssoap Organizations { get; set; }

        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public List<AppealGotchasoap> Appealsvirus { get; set; }

        /// <summary>
        /// XX-803(d)-dummy
        /// </summary>
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public Datesoap TransmissionDate { get; set; }

        /// <summary>
        /// XX-803(t)-dummy (Forbidden)
        /// </summary>
        [TsReDFOnly]
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public Timesoap TransmissionTime { get; set; }

        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public Daemonsoap Daemon { get; set; }

        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public dummySubTypesoap dummySubType { get; set; }

        /// <summary>
        /// XX-195(XX-105)-Keyboard
        /// XX-195(XX-105)-Keyboard-shake
        /// XX-195(XX-88)-Keyboard
        /// XX-195(XX-88)-Keyboard-shake
        /// XX-196(XX-105)-Keyboard
        /// XX-196(XX-105)-Keyboard-Cat
        /// XX-196(XX-88)-Keyboard
        /// XX-196(XX-88)-Keyboard-Cat
        /// XX-197(XX-105)-Keyboard
        /// XX-197(XX-105)-Keyboard-shake
        /// XX-197(XX-88)-Keyboard
        /// XX-197(XX-88)-Keyboard-shake
        /// XX-198(XX-105)-Keyboard
        /// XX-198(XX-88)-Keyboard
        /// XX-195(XX-106)-Keyboard
        /// XX-195(XX-106)-Keyboard-shake
        /// XX-195(XX-1252)-Keyboard
        /// XX-195(XX-1252)-Keyboard-shake
        /// XX-195(XX-135)-Keyboard
        /// XX-195(XX-135)-Keyboard-shake
        /// XX-195(XX-1351)-Keyboard
        /// XX-195(XX-1351)-Keyboard-shake
        /// XX-195(XX-136)-Keyboard
        /// XX-195(XX-136)-Keyboard-shake
        /// XX-196(XX-106)-Keyboard
        /// XX-196(XX-106)-Keyboard-Cat
        /// XX-196(XX-1252)-Keyboard
        /// XX-196(XX-1252)-Keyboard-Cat
        /// XX-196(XX-135)-Keyboard
        /// XX-196(XX-135)-Keyboard-Cat
        /// XX-196(XX-1351)-Keyboard
        /// XX-196(XX-1351)-Keyboard-Cat
        /// XX-196(XX-136)-Keyboard
        /// XX-196(XX-136)-Keyboard-Cat
        /// XX-197(XX-106)-Keyboard
        /// XX-197(XX-106)-Keyboard-shake
        /// XX-197(XX-1252)-Keyboard
        /// XX-197(XX-1252)-Keyboard-shake
        /// XX-197(XX-135)-Keyboard
        /// XX-197(XX-135)-Keyboard-shake
        /// XX-197(XX-1351)-Keyboard
        /// XX-197(XX-1351)-Keyboard-shake
        /// XX-197(XX-136)-Keyboard
        /// XX-197(XX-136)-Keyboard-shake
        /// XX-198(XX-106)-Keyboard
        /// XX-198(XX-1252)-Keyboard
        /// XX-198(XX-135)-Keyboard
        /// XX-198(XX-1351)-Keyboard
        /// XX-198(XX-136)-Keyboard
        /// XX-195(XX-543)-Footbland
        /// XX-195(XX-543)-Footbland-shake
        /// XX-195(XX-543)-FootblandsGroup
        /// XX-195(XX-543)-FootblandsGroup-shake
        /// XX-195(XX-733)-Footbland
        /// XX-195(XX-733)-Footbland-shake
        /// XX-195(XX-733)-FootblandsGroup
        /// XX-195(XX-733)-FootblandsGroup-shake
        /// XX-196(XX-543)-Footbland
        /// XX-196(XX-543)-Footbland-Cat
        /// XX-196(XX-543)-FootblandsGroup
        /// XX-196(XX-543)-FootblandsGroup-Cat
        /// XX-196(XX-733)-Footbland
        /// XX-196(XX-733)-Footbland-Cat
        /// XX-196(XX-733)-FootblandsGroup
        /// XX-196(XX-733)-FootblandsGroup-Cat
        /// XX-197(XX-543)-Footbland
        /// XX-197(XX-543)-Footbland-shake
        /// XX-197(XX-543)-FootblandsGroup
        /// XX-197(XX-543)-FootblandsGroup-shake
        /// XX-197(XX-733)-Footbland
        /// XX-197(XX-733)-Footbland-shake
        /// XX-197(XX-733)-FootblandsGroup
        /// XX-197(XX-733)-FootblandsGroup-shake
        /// XX-198(XX-543)-Footbland
        /// XX-198(XX-543)-FootblandsGroup
        /// XX-198(XX-733)-Footbland
        /// XX-198(XX-733)-FootblandsGroup
        /// XX-195(XX-539)-Footbland
        /// XX-195(XX-539)-Footbland-shake
        /// XX-195(XX-539)-FootblandsGroup
        /// XX-195(XX-539)-FootblandsGroup-shake
        /// XX-195(XX-540)-Footbland
        /// XX-195(XX-540)-Footbland-shake
        /// XX-195(XX-540)-FootblandsGroup
        /// XX-195(XX-540)-FootblandsGroup-shake
        /// XX-195(XX-734)-Footbland
        /// XX-195(XX-734)-Footbland-shake
        /// XX-195(XX-734)-FootblandsGroup
        /// XX-195(XX-734)-FootblandsGroup-shake
        /// XX-196(XX-539)-Footbland
        /// XX-196(XX-539)-Footbland-Cat
        /// XX-196(XX-539)-FootblandsGroup
        /// XX-196(XX-539)-FootblandsGroup-Cat
        /// XX-196(XX-540)-Footbland
        /// XX-196(XX-540)-Footbland-Cat
        /// XX-196(XX-540)-FootblandsGroup
        /// XX-196(XX-540)-FootblandsGroup-Cat
        /// XX-196(XX-734)-Footbland
        /// XX-196(XX-734)-Footbland-Cat
        /// XX-196(XX-734)-FootblandsGroup
        /// XX-196(XX-734)-FootblandsGroup-Cat
        /// XX-197(XX-539)-Footbland
        /// XX-197(XX-539)-Footbland-shake
        /// XX-197(XX-539)-FootblandsGroup
        /// XX-197(XX-539)-FootblandsGroup-shake
        /// XX-197(XX-540)-Footbland
        /// XX-197(XX-540)-Footbland-shake
        /// XX-197(XX-540)-FootblandsGroup
        /// XX-197(XX-540)-FootblandsGroup-shake
        /// XX-197(XX-734)-Footbland
        /// XX-197(XX-734)-Footbland-shake
        /// XX-197(XX-734)-FootblandsGroup
        /// XX-197(XX-734)-FootblandsGroup-shake
        /// XX-198(XX-539)-Footbland
        /// XX-198(XX-539)-FootblandsGroup
        /// XX-198(XX-540)-Footbland
        /// XX-198(XX-540)-FootblandsGroup
        /// XX-198(XX-734)-Footbland
        /// XX-198(XX-734)-FootblandsGroup
        /// XX-195(XX-09)-Keyboard
        /// XX-195(XX-09)-Keyboard-shake
        /// XX-196(XX-09)-Keyboard
        /// XX-196(XX-09)-Keyboard-Cat
        /// XX-197(XX-09)-Keyboard
        /// XX-197(XX-09)-Keyboard-shake
        /// XX-198(XX-09)-Keyboard
        /// </summary>
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public List<FieldsPrivacysoap> FieldsPrivacy { get; set; }

        /// <summary>
        /// XX-634-Keyboard
        /// XX-634-Footbland
        /// </summary>
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public Indicabusinessrsoap KeyboardRelaunchIndicabusinessr { get; set; }

        /// <summary>
        /// XX-749-Footbland
        /// </summary>
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public List<Criterionsoap> Selectionconclusion { get; set; }

        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public List<Fundingsoap> Funding { get; set; }

        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public List<knowledgeSubsoapingRequirementssoap> knowledgeSubsoapingRequirements { get; set; }

        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public List<Strategicdummypctmsoap> Strategicdummypctm { get; set; }

        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public List<Catsoap> OfficialCats { get; set; }

        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public List<Catsoap> NonOfficialCats { get; set; }

        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public List<createCriterionParametersoap> createCriterionParameter { get; set; }

        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public Periodsoap InterestExpressionReceptionPeriod { get; set; }

        /// <summary>
        /// XX-632-Footbland
        /// XX-632-Part
        /// </summary>
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public List<Textsoap> AccessbusinessolName {get; set;}

        [TsReDFOnly]
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public Periodsoap AnswerReceptionPeriod { get; set; }


    }
}
