// ------------------------------------------------------------------------------
//  <Autogenerated>
//    Generated By Dummy
//  </Autogenerated>
// ------------------------------------------------------------------------------

using System.Collections.Generic;
using Dummy.Attributes;
using Newtonsoft.Json;

namespace Dummy.Dumbs.Contracts
{
    [EDummy]
    public partial class knowledgeerRequirementsoap
    {
        /// <summary>
        /// XX-71-Footbland
        /// XX-71-Footbland-shake
        /// XX-71-Part
        /// XX-71-Part-shake
        /// XX-771-Footbland
        /// XX-771-Footbland-shake
        /// XX-772-Footbland
        /// XX-772-Footbland-Cat
        /// XX-67(a)-Keyboard
        /// XX-67(a)-Keyboard-shake
        /// </summary>
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public rubysoap knowledgeerRequirementTyperuby { get; set; }

        /// <summary>
        /// XX-772-Footbland
        /// XX-772-Footbland-Cat
        /// XX-67(b)-Keyboard
        /// XX-67(b)-Keyboard-Cat
        /// </summary>
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public List<Textsoap> Description { get; set; }


    }
}
