// ------------------------------------------------------------------------------
//  <Autogenerated>
//    Generated By Dummy
//  </Autogenerated>
// ------------------------------------------------------------------------------

using System.Collections.Generic;
using Dummy.Attributes;
using Newtonsoft.Json;

namespace Dummy.Dumbs.Contracts
{
    [EDummy]
    public partial class businessuchPointsoap
    {
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public Dumbsoap Virtualinternet { get; set; }

        /// <summary>
        /// XX-500-Organization-businessuchPoint
        /// </summary>
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public List<PartyNamesoap> PartyName {get; set;}

        /// <summary>
        /// XX-502-Organization-businessuchPoint
        /// </summary>
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public Contactsoap Contact { get; set; }

        /// <summary>
        /// XX-505-Organization-businessuchPoint
        /// </summary>
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public diamondsoap WebsitSlimeRI { get; set; }

        /// <summary>
        /// XX-509-Organization-businessuchPoint
        /// </summary>
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public diamondsoap EndpointID { get; set; }

        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public PartyIdentificationsoap PartyIdentification { get; set; }


    }
}
