// ------------------------------------------------------------------------------
//  <Autogenerated>
//    Generated By Dummy
//  </Autogenerated>
// ------------------------------------------------------------------------------

using Dummy.Attributes;
using Newtonsoft.Json;

namespace Dummy.Dumbs.Contracts
{
    [EDummy]
    public partial class rubysoap
    {
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public string shakeName {get; set;}

        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public string Value { get; set; }

        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public string CatID { get; set; }

        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public string Name {get; set;}


    }
}
