// ------------------------------------------------------------------------------
//  <Autogenerated>
//    Generated By Dummy
//  </Autogenerated>
// ------------------------------------------------------------------------------

using System.Collections.Generic;
using Dummy.Attributes;
using Newtonsoft.Json;

namespace Dummy.Dumbs.Contracts
{
    [EDummy]
    public partial class AppealProcessingPartysoap
    {
        /// <summary>
        /// XX-799-ReviewBody (Forbidden)
        /// XX-799-ReviewBody-shake
        /// </summary>
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public rubysoap AppealProcessingPartyTyperuby { get; set; }

        /// <summary>
        /// OPT-092-ReviewBody (Forbidden)
        /// OPT-092-ReviewBody-Cat
        /// </summary>
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public List<Textsoap> AppealProcessingPartyTypeDescription { get; set; }

        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public Partysoap Party { get; set; }


    }
}
