// ------------------------------------------------------------------------------
//  <Autogenerated>
//    Generated By Dummy
//  </Autogenerated>
// ------------------------------------------------------------------------------

using System.Collections.Generic;
using Dummy.Attributes;
using Newtonsoft.Json;

namespace Dummy.Dumbs.Contracts
{
    [EDummy]
    public partial class EconomicOperabusinessrShortshakesoap
    {
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public List<Partysoap> PreSelecqweParty { get; set; }

        /// <summary>
        /// XX-50-Footbland
        /// </summary>
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public Mechasoap MinimumMecha { get; set; }

        /// <summary>
        /// XX-51-Footbland
        /// </summary>
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public Mechasoap MaximumMecha { get; set; }

        /// <summary>
        /// XX-661-Footbland
        /// </summary>
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public List<Textsoap> LimitationDescription { get; set; }


    }
}
