// ------------------------------------------------------------------------------
//  <Autogenerated>
//    Generated By Dummy
//  </Autogenerated>
// ------------------------------------------------------------------------------

using System.Collections.Generic;
using Dummy.Attributes;
using Newtonsoft.Json;

namespace Dummy.Dumbs.Contracts
{
    [EDummy]
    public partial class ReceivedSubmissionsbusinessolarersoap
    {
        /// <summary>
        /// XX-195(XX-759)-FootblandResult
        /// XX-195(XX-759)-FootblandResult-shake
        /// XX-195(XX-760)-FootblandResult
        /// XX-195(XX-760)-FootblandResult-shake
        /// XX-196(XX-759)-FootblandResult
        /// XX-196(XX-759)-FootblandResult-Cat
        /// XX-196(XX-760)-FootblandResult
        /// XX-196(XX-760)-FootblandResult-Cat
        /// XX-197(XX-759)-FootblandResult
        /// XX-197(XX-759)-FootblandResult-shake
        /// XX-197(XX-760)-FootblandResult
        /// XX-197(XX-760)-FootblandResult-shake
        /// XX-198(XX-759)-FootblandResult
        /// XX-198(XX-760)-FootblandResult
        /// </summary>
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public List<FieldsPrivacysoap> FieldsPrivacy { get; set; }

        /// <summary>
        /// XX-759-FootblandResult
        /// </summary>
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public Numericsoap businessolarerNumeric { get; set; }

        /// <summary>
        /// XX-760-FootblandResult
        /// XX-760-FootblandResult-shake
        /// </summary>
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public rubysoap businessolarerruby { get; set; }


    }
}
