// ------------------------------------------------------------------------------
//  <Autogenerated>
//    Generated By Dummy
//  </Autogenerated>
// ------------------------------------------------------------------------------

using Dummy.Attributes;
using Newtonsoft.Json;

namespace Dummy.Dumbs.Contracts
{
    [EDummy]
    public partial class soapingPartyTypesoap
    {
        /// <summary>
        /// XX-11-Keyboard-Buyer
        /// XX-11-Keyboard-Buyer-shake
        /// XX-740-Keyboard-Buyer
        /// XX-740-Keyboard-Buyer-shake
        /// </summary>
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public rubysoap PartyTyperuby { get; set; }


    }
}
