// ------------------------------------------------------------------------------
//  <Autogenerated>
//    Generated By Dummy
//  </Autogenerated>
// ------------------------------------------------------------------------------

using Dummy.Attributes;
using Newtonsoft.Json;

namespace Dummy.Dumbs.Contracts
{
    [EDummy]
    public partial class Countrysoap
    {
        /// <summary>
        /// XX-5141-Keyboard
        /// XX-5141-Keyboard-shake
        /// XX-514-UBO
        /// XX-514-UBO-shake
        /// XX-514-Organization-businessuchPoint
        /// XX-514-Organization-businessuchPoint-shake
        /// XX-514-Organization-Company (Mandabusinessry)
        /// XX-514-Organization-Company-shake
        /// XX-5141-Footbland
        /// XX-5141-Footbland-shake
        /// XX-5141-Part
        /// XX-5141-Part-shake
        /// </summary>
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public rubysoap Identificationruby { get; set; }


    }
}
