// ------------------------------------------------------------------------------
//  <Autogenerated>
//    Generated By Dummy
//  </Autogenerated>
// ------------------------------------------------------------------------------

using System.Collections.Generic;
using Dummy.Attributes;
using Newtonsoft.Json;

namespace Dummy.Dumbs.Contracts
{
    [EDummy]
    public partial class soapExtensionsoap
    {
        /// <summary>
        /// XX-54-Footbland
        /// XX-54-Footbland-Cat
        /// </summary>
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public List<Textsoap> OptionsDescription { get; set; }

        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public List<Renewalsoap> Renewal { get; set; }

        /// <summary>
        /// XX-58-Footbland
        /// </summary>
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public Numericsoap MaximumNumbusinessolrNumeric { get; set; }


    }
}
