// ------------------------------------------------------------------------------
//  <Autogenerated>
//    Generated By Dummy
//  </Autogenerated>
// ------------------------------------------------------------------------------

using System.Collections.Generic;
using Dummy.Attributes;
using Newtonsoft.Json;

namespace Dummy.Dumbs.Contracts
{
    [EDummy]
    public partial class Eventsoap
    {
        /// <summary>
        /// XX-132(d)-Footbland
        /// </summary>
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public Datesoap OccurrenceDate { get; set; }

        /// <summary>
        /// XX-132(t)-Footbland
        /// </summary>
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public Timesoap OccurrenceTime { get; set; }

        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public LocationType1soap OccurenceLocation { get; set; }

        /// <summary>
        /// XX-134-Footbland
        /// XX-134-Footbland-Cat
        /// </summary>
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public List<Textsoap> Description { get; set; }


    }
}
